spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/alegakom/ms-config-properties
          search-paths:
            - "/{application}/{profile}"